### ISSUE TITLE
Add proxy support requirement to spec

### ISSUE THREAD

**Issue by leggetter** [Nexmo/server-sdk-specification#2]
I've seen this so many times in support and via GitHub requests that making it very clear how to set up a proxy is an essential requirement. We should have a "How to set a Proxy" in the README too.

I'd generally make it part of the initialization for the library. If you can pass in custom HTTP clients then I'd have a standard interface that all custom clients must implement which includes setting a proxy.

**Comment by tjlytle** [comment]
> Must allow override of the base URL(s) (currently there are multiple base urls).

This part of the spec already requires simplistic proxying by URL replacement (works with Runscope / Charles Proxy, etc). Simple implementation in the [PHP library here](https://github.com/Nexmo/nexmo-php/blob/b5374a8e926fc22da9fdf614a99dd9adcfc35a17/src/Client.php#L213-L222).

Making it a requirement that the HTTP client supported proxying (since the libraries should be using a well supported HTTP client), should work for this - right? For example, the PHP library supports that as well, as it ships with Guzzle, and that can be configured for a proxy [when creating a client](http://docs.guzzlephp.org/en/5.3/clients.html#creating-a-client).
